### ISSUE TITLE
how to implement it in your project?

### ISSUE THREAD

**Issue by L1nker2** [akon47/SimpleTcp#18]
hello, I want to create my own client-server application, but I still can’t learn multithreading and sockets. I found your repository and it seemed to me that this is a great solution to my problem. only now I'm a beginner and I can't quite figure out how to use it in my project? Can it somehow be connected through the package manager?

**Comment by Bausahab** [comment]
https://github.com/Swazimodo/TCPUtility.git

this is the base on witch whole applicaion is communicating... 

I have developed project based upon this.. it has following...
A Socket handling librery...
A shared model librery...
A Server windows applicaion
A Client windows applicaion..

TCP communication machnism is using thread distribution on client connections. Clients have assigned with unique guid, this id is useful to identify certain client . A base class to identify  data message and its type... being transfer between.
 :)
